### ISSUE TITLE
Search or translate: What is meant by "code"

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ppt-frontend#13]
You have options to search for term or code but it is not clear what these mean

**Comment by lisssek** [comment]
<img width="489" alt="screen shot 2016-11-10 at 15 29 07" src="https://cloud.githubusercontent.com/assets/2270210/20182676/7d786894-a75a-11e6-8832-3f2e47b2bdd8.png">
<img width="460" alt="screen shot 2016-11-10 at 15 29 12" src="https://cloud.githubusercontent.com/assets/2270210/20182680/7fbe49ac-a75a-11e6-8dbc-ff16b93d0a8d.png">
