### ISSUE TITLE
Search and translate freeze sometimes for no reason

### ISSUE THREAD

**Issue by lisssek** [devinit/ppt-frontend#21]
<img width="1516" alt="screen shot 2017-01-17 at 15 01 30" src="https://cloud.githubusercontent.com/assets/2270210/22025563/e43fdcce-dcc5-11e6-81a3-a33fb1db8ebc.png">

**Comment by dw8547** [comment]
@lisssek, that might have something to do with the Tomcat memory allocation (how much of the RAM we've reserved for PoolParty). Will investigate today & keep you posted.

**Comment by lisssek** [comment]
@dw8547 The problem is now solved. Thank you.

**Comment by dw8547** [comment]
Please reopen if the problem comes back.
