### ISSUE TITLE
Mouse over on simple search

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ppt-frontend#7]
to explain what it is searching and what you will get in return

**Comment by lisssek** [comment]
Done.

**Comment by lisssek** [comment]
Proposed text for the mouse- over "The simple search lets users find all concepts that contain a search term or code. For example, if you search for a term “agriculture”, a list of concepts containing the word “agriculture” will be returned. The simple search can be carried out either within a specific project (such as “Sectors”) or across projects. "

**Comment by lisssek** [comment]
<img width="897" alt="7" src="https://cloud.githubusercontent.com/assets/2270210/20479052/a27a468a-afd4-11e6-89e8-f0afb9ae312c.png">

**Comment by lisssek** [comment]
<img width="951" alt="7" src="https://cloud.githubusercontent.com/assets/2270210/20479234/63d97ed6-afd5-11e6-8900-618331e9a8f8.png">

**Comment by lisssek** [comment]
<img width="951" alt="7" src="https://cloud.githubusercontent.com/assets/2270210/20479328/adaf6764-afd5-11e6-805d-8caf6c6aee8f.png">
