### ISSUE TITLE
"View More / View Less" bar on concept record

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ppt-frontend#8]
Red text on black is too small and cannot be seen. User can't tell that there is more to view

**Comment by lisssek** [comment]
OK. We will change it to white.

**Comment by lisssek** [comment]
@epicallan this is on the regular pages of the PPT. For example: 
<img width="1099" alt="screen shot 2016-11-21 at 10 18 38" src="https://cloud.githubusercontent.com/assets/2270210/20478873/ee9e8ed2-afd3-11e6-99e2-bb35b881e5ba.png">
